//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alergias.
        /// </summary>
        public static string Alergias {
            get {
                return ResourceManager.GetString("Alergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string Aluno_btn {
            get {
                return ResourceManager.GetString("Aluno_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aulas.
        /// </summary>
        public static string Aulas_btn {
            get {
                return ResourceManager.GetString("Aulas_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliação.
        /// </summary>
        public static string Avaliacao_btn {
            get {
                return ResourceManager.GetString("Avaliacao_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string btn_salvar {
            get {
                return ResourceManager.GetString("btn_salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador.
        /// </summary>
        public static string Colaborador_btn {
            get {
                return ResourceManager.GetString("Colaborador_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Admissão.
        /// </summary>
        public static string DateAdmissao {
            get {
                return ResourceManager.GetString("DateAdmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Avaliação.
        /// </summary>
        public static string DateDataAvaliacao {
            get {
                return ResourceManager.GetString("DateDataAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada.
        /// </summary>
        public static string DateEntrada {
            get {
                return ResourceManager.GetString("DateEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fim.
        /// </summary>
        public static string DateFim {
            get {
                return ResourceManager.GetString("DateFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio.
        /// </summary>
        public static string DateInicio {
            get {
                return ResourceManager.GetString("DateInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nascimento.
        /// </summary>
        public static string DateNascimento {
            get {
                return ResourceManager.GetString("DateNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saída.
        /// </summary>
        public static string DateSaida {
            get {
                return ResourceManager.GetString("DateSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diabetes.
        /// </summary>
        public static string Diabetes {
            get {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frequência.
        /// </summary>
        public static string Frequencia_btn {
            get {
                return ResourceManager.GetString("Frequencia_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravidez.
        /// </summary>
        public static string Gravidez {
            get {
                return ResourceManager.GetString("Gravidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Principal.
        /// </summary>
        public static string Home_btn {
            get {
                return ResourceManager.GetString("Home_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/região alterado com sucesso!.
        /// </summary>
        public static string IdiomaAlteradoComSucesso {
            get {
                return ResourceManager.GetString("IdiomaAlteradoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        public static string IdiomaRegiao {
            get {
                return ResourceManager.GetString("IdiomaRegiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Admissão.
        /// </summary>
        public static string LabelAdmissao {
            get {
                return ResourceManager.GetString("LabelAdmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura.
        /// </summary>
        public static string LabelAltura {
            get {
                return ResourceManager.GetString("LabelAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Direito.
        /// </summary>
        public static string LabelAntebracoDir {
            get {
                return ResourceManager.GetString("LabelAntebracoDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Esquerdo.
        /// </summary>
        public static string LabelAntebracoEsq {
            get {
                return ResourceManager.GetString("LabelAntebracoEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        public static string LabelBairro {
            get {
                return ResourceManager.GetString("LabelBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biceps Direito.
        /// </summary>
        public static string LabelBicepsDir {
            get {
                return ResourceManager.GetString("LabelBicepsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biceps Esquerdo.
        /// </summary>
        public static string LabelBicepsEsq {
            get {
                return ResourceManager.GetString("LabelBicepsEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        public static string LabelCep {
            get {
                return ResourceManager.GetString("LabelCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep Logradouro.
        /// </summary>
        public static string LabelCepLogradouro {
            get {
                return ResourceManager.GetString("LabelCepLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string LabelCidade {
            get {
                return ResourceManager.GetString("LabelCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cintura.
        /// </summary>
        public static string LabelCintura {
            get {
                return ResourceManager.GetString("LabelCintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        public static string LabelComplemento {
            get {
                return ResourceManager.GetString("LabelComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Direita.
        /// </summary>
        public static string LabelCoxaDir {
            get {
                return ResourceManager.GetString("LabelCoxaDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Esquerda.
        /// </summary>
        public static string LabelCoxaEsq {
            get {
                return ResourceManager.GetString("LabelCoxaEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf.
        /// </summary>
        public static string LabelCpf {
            get {
                return ResourceManager.GetString("LabelCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf Aluno.
        /// </summary>
        public static string LabelCpfAluno {
            get {
                return ResourceManager.GetString("LabelCpfAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        public static string LabelData {
            get {
                return ResourceManager.GetString("LabelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada.
        /// </summary>
        public static string LabelEntrada {
            get {
                return ResourceManager.GetString("LabelEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fim.
        /// </summary>
        public static string LabelFim {
            get {
                return ResourceManager.GetString("LabelFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id.
        /// </summary>
        public static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id Aluno.
        /// </summary>
        public static string LabelIdAluno {
            get {
                return ResourceManager.GetString("LabelIdAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id Logradouro.
        /// </summary>
        public static string LabelIdLogradouro {
            get {
                return ResourceManager.GetString("LabelIdLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imc.
        /// </summary>
        public static string LabelImc {
            get {
                return ResourceManager.GetString("LabelImc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio.
        /// </summary>
        public static string LabelInicio {
            get {
                return ResourceManager.GetString("LabelInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Laudo Médico.
        /// </summary>
        public static string LabelLaudoMedico {
            get {
                return ResourceManager.GetString("LabelLaudoMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lesões Musculares.
        /// </summary>
        public static string LabelLesões_Musculares {
            get {
                return ResourceManager.GetString("LabelLesões Musculares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string LabelLogradouro {
            get {
                return ResourceManager.GetString("LabelLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Gorda.
        /// </summary>
        public static string LabelMassaGorda {
            get {
                return ResourceManager.GetString("LabelMassaGorda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Magra.
        /// </summary>
        public static string LabelMassaMagra {
            get {
                return ResourceManager.GetString("LabelMassaMagra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nascimento.
        /// </summary>
        public static string LabelNascimento {
            get {
                return ResourceManager.GetString("LabelNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string LabelNome {
            get {
                return ResourceManager.GetString("LabelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Aluno.
        /// </summary>
        public static string LabelNomeAluno {
            get {
                return ResourceManager.GetString("LabelNomeAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero.
        /// </summary>
        public static string LabelNumero {
            get {
                return ResourceManager.GetString("LabelNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo.
        /// </summary>
        public static string LabelObjetivo {
            get {
                return ResourceManager.GetString("LabelObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação Restrição.
        /// </summary>
        public static string LabelObservacaoRestricao {
            get {
                return ResourceManager.GetString("LabelObservacaoRestricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações.
        /// </summary>
        public static string LabelObservacoes {
            get {
                return ResourceManager.GetString("LabelObservacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pais.
        /// </summary>
        public static string LabelPais {
            get {
                return ResourceManager.GetString("LabelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Direita.
        /// </summary>
        public static string LabelPanturrilhaDir {
            get {
                return ResourceManager.GetString("LabelPanturrilhaDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Esquerda.
        /// </summary>
        public static string LabelPanturrilhaEsq {
            get {
                return ResourceManager.GetString("LabelPanturrilhaEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual Gordura.
        /// </summary>
        public static string LabelPercentualGordura {
            get {
                return ResourceManager.GetString("LabelPercentualGordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string LabelPeso {
            get {
                return ResourceManager.GetString("LabelPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso Ideal.
        /// </summary>
        public static string LabelPesoIdeal {
            get {
                return ResourceManager.GetString("LabelPesoIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano.
        /// </summary>
        public static string LabelPlano {
            get {
                return ResourceManager.GetString("LabelPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadril.
        /// </summary>
        public static string LabelQuadril {
            get {
                return ResourceManager.GetString("LabelQuadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re Senha.
        /// </summary>
        public static string LabelReSenha {
            get {
                return ResourceManager.GetString("LabelReSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restrições.
        /// </summary>
        public static string LabelRestricoes {
            get {
                return ResourceManager.GetString("LabelRestricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saída.
        /// </summary>
        public static string LabelSaida {
            get {
                return ResourceManager.GetString("LabelSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string LabelSenha {
            get {
                return ResourceManager.GetString("LabelSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string LabelTelefone {
            get {
                return ResourceManager.GetString("LabelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Torax.
        /// </summary>
        public static string LabelTorax {
            get {
                return ResourceManager.GetString("LabelTorax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uf.
        /// </summary>
        public static string LabelUf {
            get {
                return ResourceManager.GetString("LabelUf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Labirinto.
        /// </summary>
        public static string Labirinto {
            get {
                return ResourceManager.GetString("Labirinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lesões Musculares.
        /// </summary>
        public static string LesoesMusculares {
            get {
                return ResourceManager.GetString("LesoesMusculares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logon/Logoff.
        /// </summary>
        public static string Login_btn {
            get {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string Logradouro_btn {
            get {
                return ResourceManager.GetString("Logradouro_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        public static string Matricula_btn {
            get {
                return ResourceManager.GetString("Matricula_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja fechar a janela?.
        /// </summary>
        public static string MsgConfirmarFechamento {
            get {
                return ResourceManager.GetString("MsgConfirmarFechamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma.
        /// </summary>
        public static string Nenhuma {
            get {
                return ResourceManager.GetString("Nenhuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outras.
        /// </summary>
        public static string Outras {
            get {
                return ResourceManager.GetString("Outras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressão Alta.
        /// </summary>
        public static string PressaoAlta {
            get {
                return ResourceManager.GetString("PressaoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problemas Cardíacos.
        /// </summary>
        public static string ProblemasCardiacos {
            get {
                return ResourceManager.GetString("ProblemasCardiacos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problemas Respiratórios.
        /// </summary>
        public static string ProblemasRespiratorios {
            get {
                return ResourceManager.GetString("ProblemasRespiratorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        public static string RdbAdministrador {
            get {
                return ResourceManager.GetString("RdbAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anual.
        /// </summary>
        public static string RdbAnual {
            get {
                return ResourceManager.GetString("RdbAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atendente.
        /// </summary>
        public static string RdbAtendente {
            get {
                return ResourceManager.GetString("RdbAtendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clt.
        /// </summary>
        public static string RdbClt {
            get {
                return ResourceManager.GetString("RdbClt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estágio.
        /// </summary>
        public static string RdbEstagio {
            get {
                return ResourceManager.GetString("RdbEstagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instrutor.
        /// </summary>
        public static string RdbInstrutor {
            get {
                return ResourceManager.GetString("RdbInstrutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensal.
        /// </summary>
        public static string RdbMensal {
            get {
                return ResourceManager.GetString("RdbMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Semestral.
        /// </summary>
        public static string RdbSemestral {
            get {
                return ResourceManager.GetString("RdbSemestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trimestral.
        /// </summary>
        public static string RdbTrimestral {
            get {
                return ResourceManager.GetString("RdbTrimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remédios Uso Continuo.
        /// </summary>
        public static string RemediosUsoContinuo {
            get {
                return ResourceManager.GetString("RemediosUsoContinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string Senha_btn {
            get {
                return ResourceManager.GetString("Senha_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação de Saída.
        /// </summary>
        public static string TituloConfirmarFechamento {
            get {
                return ResourceManager.GetString("TituloConfirmarFechamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinos.
        /// </summary>
        public static string Treinos_btn {
            get {
                return ResourceManager.GetString("Treinos_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura.
        /// </summary>
        public static string txtAltura {
            get {
                return ResourceManager.GetString("txtAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Direito.
        /// </summary>
        public static string txtAntebracoDir {
            get {
                return ResourceManager.GetString("txtAntebracoDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Esquerdo.
        /// </summary>
        public static string txtAntebracoEsq {
            get {
                return ResourceManager.GetString("txtAntebracoEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biceps Direito.
        /// </summary>
        public static string txtBicepsDir {
            get {
                return ResourceManager.GetString("txtBicepsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biceps Esquerdo.
        /// </summary>
        public static string txtBicepsEsq {
            get {
                return ResourceManager.GetString("txtBicepsEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo.
        /// </summary>
        public static string txtBlockObjetivo {
            get {
                return ResourceManager.GetString("txtBlockObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação Restrição.
        /// </summary>
        public static string txtBlockObservacaoRestricao {
            get {
                return ResourceManager.GetString("txtBlockObservacaoRestricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações.
        /// </summary>
        public static string txtBlockObservacoes {
            get {
                return ResourceManager.GetString("txtBlockObservacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        public static string txtCep {
            get {
                return ResourceManager.GetString("txtCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep Logradouro.
        /// </summary>
        public static string txtCepLogradouro {
            get {
                return ResourceManager.GetString("txtCepLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string txtCidade {
            get {
                return ResourceManager.GetString("txtCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cintura.
        /// </summary>
        public static string txtCintura {
            get {
                return ResourceManager.GetString("txtCintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        public static string txtComplemento {
            get {
                return ResourceManager.GetString("txtComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Direita.
        /// </summary>
        public static string txtCoxaDir {
            get {
                return ResourceManager.GetString("txtCoxaDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf.
        /// </summary>
        public static string txtCpf {
            get {
                return ResourceManager.GetString("txtCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf Aluno.
        /// </summary>
        public static string txtCpfAluno {
            get {
                return ResourceManager.GetString("txtCpfAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id.
        /// </summary>
        public static string txtId {
            get {
                return ResourceManager.GetString("txtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id Aluno.
        /// </summary>
        public static string txtIdAluno {
            get {
                return ResourceManager.GetString("txtIdAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id Logradouro.
        /// </summary>
        public static string txtIdLogradouro {
            get {
                return ResourceManager.GetString("txtIdLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imc.
        /// </summary>
        public static string txtImc {
            get {
                return ResourceManager.GetString("txtImc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Laudo Médico.
        /// </summary>
        public static string txtLaudoMedico {
            get {
                return ResourceManager.GetString("txtLaudoMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string txtLogradouro {
            get {
                return ResourceManager.GetString("txtLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Gorda.
        /// </summary>
        public static string txtMassaGorda {
            get {
                return ResourceManager.GetString("txtMassaGorda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Magra.
        /// </summary>
        public static string txtMassaMagra {
            get {
                return ResourceManager.GetString("txtMassaMagra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string txtNome {
            get {
                return ResourceManager.GetString("txtNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Aluno.
        /// </summary>
        public static string txtNomeAluno {
            get {
                return ResourceManager.GetString("txtNomeAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero.
        /// </summary>
        public static string txtNumero {
            get {
                return ResourceManager.GetString("txtNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pais.
        /// </summary>
        public static string txtPais {
            get {
                return ResourceManager.GetString("txtPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Direita.
        /// </summary>
        public static string txtPanturrilhaDir {
            get {
                return ResourceManager.GetString("txtPanturrilhaDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Esquerda.
        /// </summary>
        public static string txtPanturrilhaEsq {
            get {
                return ResourceManager.GetString("txtPanturrilhaEsq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual Gordura.
        /// </summary>
        public static string txtPercentualGordura {
            get {
                return ResourceManager.GetString("txtPercentualGordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string txtPeso {
            get {
                return ResourceManager.GetString("txtPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso Ideal.
        /// </summary>
        public static string txtPesoIdeal {
            get {
                return ResourceManager.GetString("txtPesoIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadril.
        /// </summary>
        public static string txtQuadril {
            get {
                return ResourceManager.GetString("txtQuadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re Senha.
        /// </summary>
        public static string txtReSenha {
            get {
                return ResourceManager.GetString("txtReSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string txtSenha {
            get {
                return ResourceManager.GetString("txtSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string txtTelefone {
            get {
                return ResourceManager.GetString("txtTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Torax.
        /// </summary>
        public static string txtTorax {
            get {
                return ResourceManager.GetString("txtTorax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uf.
        /// </summary>
        public static string txtUf {
            get {
                return ResourceManager.GetString("txtUf", resourceCulture);
            }
        }
    }
}
